import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideNav from './components/SideNav'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'; 
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider>
      <div style={{ display: 'flex' }}>
          <SideNav />
          <main>
            {children}
          </main>
        </div>
      </AppRouterCacheProvider>
      </body>
    </html>
  )
}
